export const FETCH_FOOD_DETAIL_REQUEST = 'FETCH_FOOD_DETAIL_REQUEST';
export const FETCH_FOOD_DETAIL_SUCCESS = 'FETCH_FOOD_DETAIL_SUCCESS';
export const FETCH_FOOD_DETAIL_FAILURE = 'FETCH_FOOD_DETAIL_FAILURE';
